/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact {
  'id' : string,
  'name' : string,
  'note' : string,
  'phone' : string,
}
export interface LocationPoint {
  'latitude' : number,
  'longitude' : number,
  'timestamp' : bigint,
  'accuracy' : number,
}
export interface SOSEvent {
  'id' : string,
  'startTime' : bigint,
  'endTime' : [] | [bigint],
  'shareToken' : string,
  'audioBlobIds' : Array<string>,
  'isActive' : boolean,
  'locationHistory' : Array<LocationPoint>,
  'emergencyMessage' : string,
}
export interface UserProfile {
  'displayName' : string,
  'emergencyMessage' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAudioToEvent' : ActorMethod<[string, string], undefined>,
  'addContact' : ActorMethod<[Contact], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSOSEvent' : ActorMethod<
    [string],
    { 'id' : string, 'shareToken' : string }
  >,
  'deleteContact' : ActorMethod<[string], undefined>,
  'getActiveLocations' : ActorMethod<[string], Array<LocationPoint>>,
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getEvent' : ActorMethod<[string], SOSEvent>,
  'getLocations' : ActorMethod<[string], Array<LocationPoint>>,
  'getSOSEvents' : ActorMethod<[], Array<SOSEvent>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'stopEvent' : ActorMethod<[string, string], string>,
  'updateContact' : ActorMethod<[Contact], undefined>,
  'updateLocation' : ActorMethod<[string, string, LocationPoint], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];