/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Contact = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'note' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LocationPoint = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
  'timestamp' : IDL.Int,
  'accuracy' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'emergencyMessage' : IDL.Text,
});
export const SOSEvent = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Int,
  'endTime' : IDL.Opt(IDL.Int),
  'shareToken' : IDL.Text,
  'audioBlobIds' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'locationHistory' : IDL.Vec(LocationPoint),
  'emergencyMessage' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAudioToEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addContact' : IDL.Func([Contact], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSOSEvent' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'id' : IDL.Text, 'shareToken' : IDL.Text })],
      [],
    ),
  'deleteContact' : IDL.Func([IDL.Text], [], []),
  'getActiveLocations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LocationPoint)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getEvent' : IDL.Func([IDL.Text], [SOSEvent], ['query']),
  'getLocations' : IDL.Func([IDL.Text], [IDL.Vec(LocationPoint)], ['query']),
  'getSOSEvents' : IDL.Func([], [IDL.Vec(SOSEvent)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'stopEvent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'updateContact' : IDL.Func([Contact], [], []),
  'updateLocation' : IDL.Func(
      [IDL.Text, IDL.Text, LocationPoint],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Contact = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'note' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LocationPoint = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
    'timestamp' : IDL.Int,
    'accuracy' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'emergencyMessage' : IDL.Text,
  });
  const SOSEvent = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Int,
    'endTime' : IDL.Opt(IDL.Int),
    'shareToken' : IDL.Text,
    'audioBlobIds' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'locationHistory' : IDL.Vec(LocationPoint),
    'emergencyMessage' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAudioToEvent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addContact' : IDL.Func([Contact], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSOSEvent' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'id' : IDL.Text, 'shareToken' : IDL.Text })],
        [],
      ),
    'deleteContact' : IDL.Func([IDL.Text], [], []),
    'getActiveLocations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LocationPoint)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getEvent' : IDL.Func([IDL.Text], [SOSEvent], ['query']),
    'getLocations' : IDL.Func([IDL.Text], [IDL.Vec(LocationPoint)], ['query']),
    'getSOSEvents' : IDL.Func([], [IDL.Vec(SOSEvent)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'stopEvent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'updateContact' : IDL.Func([Contact], [], []),
    'updateLocation' : IDL.Func(
        [IDL.Text, IDL.Text, LocationPoint],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };